version: "3.9"

services:
  oracledb:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracledb
    environment:
      ORACLE_PWD: "${ORACLE_PASSWORD}"
      ORACLE_SID: "FREE"
      ORACLE_PDB: "FREEPDB1"
      ORACLE_MEMORY: "2048"
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oradata:/opt/oracle/oradata
      - ./db_repo:/opt/oracle/scripts/startup:ro
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s sys/${ORACLE_PASSWORD}@localhost:1521/FREEPDB1 as sysdba || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 30

  java-api:
    build:
      context: ./java-api
      dockerfile: Dockerfile
    container_name: java-api
    depends_on:
      oracledb:
        condition: service_healthy
    environment:
      DB_URL: "jdbc:oracle:thin:@oracledb:1521/FREEPDB1"
      DB_USER: "${ORACLE_APP_USER}"
      DB_PASS: "${ORACLE_APP_PASS}"
    ports:
      - "8081:8080"

  dotnet-api:
    build:
      context: ./dotnet-api
      dockerfile: Dockerfile
    container_name: dotnet-api
    depends_on:
      oracledb:
        condition: service_healthy
    environment:
      ConnectionStrings__Oracle: "User Id=${ORACLE_APP_USER};Password=${ORACLE_APP_PASS};Data Source=oracledb:1521/FREEPDB1;"
    ports:
      - "8082:8080"

volumes:
  oradata:
