WHENEVER SQLERROR EXIT SQL.SQLCODE
-- Entrar na PDB
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Cria o usuário se não existir
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM dba_users WHERE username='APPUSER';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER appuser IDENTIFIED BY "AppPass#2025"';
  END IF;

  -- Grants básicos para appuser
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO appuser';
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO appuser';
  EXECUTE IMMEDIATE 'ALTER USER appuser QUOTA UNLIMITED ON USERS';
END;
/
EXIT
