ALTER SESSION SET CONTAINER = FREEPDB1;
CREATE USER APPUSER IDENTIFIED BY "SenhaApp123" ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO APPUSER;
ALTER USER APPUSER QUOTA UNLIMITED ON USERS;
-- opcional: crie aqui suas tabelas para o app
-- CREATE TABLE APPUSER.EXEMPLO(ID NUMBER PRIMARY KEY, NOME VARCHAR2(50));
