WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER=FREEPDB1;
CREATE USER APP IDENTIFIED BY "SenhaApp123";
GRANT CONNECT, RESOURCE TO APP;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO APP;
-- opcional: se precisar de tablespace dedicada, ajuste conforme a imagem
